/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./client/index.html",
    "./client/src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'background-1': '#252525',
        'background-2': '#9A9A9A',
        'button-1': '#3B3B3B',
        'button-2': '#FF0000',
        'input-1': '#3B3B3B',
        'card-1': '#FD99FF',
        'card-2': '#FF9E9E',
        'card-3': '#91F48F',
        'card-4': '#FFF599',
        'card-5': '#9EFFFF',
        'card-6': '#B69CFF',
        'color-1': '#FFFFFF',
        'color-2': '#CFCFCF',
        'color-3': '#9A9A9A',
        'color-4': '#000000',
      },
      fontFamily: {
        'nunito-black': ['Nunito-Black', 'sans-serif'],
        'nunito-black-italic': ['Nunito-BlackItalic', 'sans-serif'],
        'nunito-bold': ['Nunito-Bold', 'sans-serif'],
        'nunito-bold-italic': ['Nunito-BoldItalic', 'sans-serif'],
        'nunito-extrabold': ['Nunito-ExtraBold', 'sans-serif'],
        'nunito-extrabold-italic': ['Nunito-ExtraBoldItalic', 'sans-serif'],
        'nunito-extralight': ['Nunito-ExtraLight', 'sans-serif'],
        'nunito-extralight-italic': ['Nunito-ExtraLightItalic', 'sans-serif'],
        'nunito-italic': ['Nunito-Italic', 'sans-serif'],
        'nunito-light-italic': ['Nunito-LightItalic', 'sans-serif'],
        'nunito-medium': ['Nunito-Medium', 'sans-serif'],
        'nunito-medium-italic': ['Nunito-MediumItalic', 'sans-serif'],
        'nunito-regular': ['Nunito-Regular', 'sans-serif'],
        'nunito-semibold': ['Nunito-SemiBold', 'sans-serif'],
        'nunito-semibold-italic': ['Nunito-SemiBoldItalic', 'sans-serif'],
      },
    },
  },
  plugins: [],
}